script for creating frontned automatically

diff --git a/Frontend b/Frontend
--- a/Frontend
+++ b/Frontend
@@ -6,19 +6,57 @@ LOG=/tmp/roboshop.log
 
 echo -e "\e[32m install nginx\e[0m"
 yum install nginx -y &>>${LOG}
+
+if [ $? -eq 0 ]
+then
+  echo "Success"
+else
+  echo "failure"
+fi
+
 systemctl enable nginx &>>${LOG}
 systemctl start nginx &>>${LOG}
 
 echo -e "\e[33m remove old content\e[0m"
+
 rm -rf /usr/share/nginx/html/* &>>${LOG}
 
+if [ $? -eq 0 ]
+then
+  echo "Success"
+else
+  echo "failure"
+fi
+
 echo -e "\e[32m Download Frontend content\e[0m"
+
 curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${LOG}
 cd /usr/share/nginx/html &>>${LOG}
+
+if [ $? -eq 0 ]
+then
+  echo "Success"
+else
+  echo "failure"
+fi
 
 echo -e "\e[31m unziping frontend contenet in html\e[0m"
 unzip /tmp/frontend.zip &>>${LOG}
 
+if [ $? -eq 0 ]
+then
+  echo "Success"
+else
+  echo "failure"
+fi
+
 echo -e "\e[32m copying roboshop nginxfile\e[0m"
 cp ${script_location}/files/nginxroboshop.conf /etc/nginx/default.d/roboshop.conf
+
+if [ $? -eq 0 ]
+then
+  echo "Success"
+else
+  echo "failure"
+fi
 systemctl restart  nginx &>>${LOG}
